[package]
name = "egl"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
build = "build.rs"

[build-dependencies]
gl_generator = "*"
khronos_api = "*"

[dependencies]
gl_common = "*"
libc = "*"